# Generated by Django 4.2.30 on 2026-09-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMPLOYED", "Employed"),
                            ("SELF_EMPLOYED", "Self-employed"),
                            ("APPRENTICE", "Apprentice"),
                            ("SEEKING", "Seeking employment"),
                            ("HIGHER_EDUCATION", "Higher education"),
                            ("CONTINUING_TRAINING", "Continuing training"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                ("employer_email", models.EmailField(blank=True, max_length=254)),
                ("business_type", models.CharField(blank=True, max_length=120)),
                ("job_role", models.CharField(blank=True, max_length=120)),
                ("sector", models.CharField(blank=True, max_length=80)),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NDB", "Nandurbar"),
                            ("DHL", "Dhule"),
                            ("JLG", "Jalgaon"),
                            ("BLD", "Buldhana"),
                            ("AKL", "Akola"),
                            ("AMR", "Amravati"),
                            ("NGP", "Nagpur"),
                            ("BHN", "Bhandara"),
                            ("GND", "Gondia"),
                            ("PLG", "Palghar"),
                            ("NSK", "Nashik"),
                            ("AUR", "Chh. Sambhajinagar"),
                            ("JLN", "Jalna"),
                            ("WSM", "Washim"),
                            ("YTL", "Yavatmal"),
                            ("WRD", "Wardha"),
                            ("CHD", "Chandrapur"),
                            ("GDC", "Gadchiroli"),
                            ("MSU", "Mumbai Suburban"),
                            ("THN", "Thane"),
                            ("AHM", "Ahilyanagar"),
                            ("BED", "Beed"),
                            ("PBN", "Parbhani"),
                            ("HNG", "Hingoli"),
                            ("NDD", "Nanded"),
                            ("MUM", "Mumbai City"),
                            ("RGD", "Raigad"),
                            ("PNE", "Pune"),
                            ("DRS", "Dharashiv"),
                            ("LTR", "Latur"),
                            ("RTN", "Ratnagiri"),
                            ("STR", "Satara"),
                            ("SLP", "Solapur"),
                            ("SDG", "Sindhudurg"),
                            ("KLP", "Kolhapur"),
                            ("SNG", "Sangli"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("GIG", "Gig / freelance"),
                            ("SEASONAL", "Seasonal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "monthly_income",
                    models.PositiveIntegerField(
                        blank=True, help_text="INR per month", null=True
                    ),
                ),
                ("related_skills", models.JSONField(blank=True, default=list)),
                ("consent_for_verification", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("SELF_REPORTED", "Self-reported"),
                            ("REQUESTED", "Verification requested"),
                            ("CONFIRMED", "Employer confirmed"),
                            ("REJECTED", "Employer rejected"),
                            ("DISPUTED", "Disputed"),
                            ("UNABLE", "Unable to verify"),
                            ("MANUAL_REVIEW", "Manual review"),
                        ],
                        default="SELF_REPORTED",
                        max_length=15,
                    ),
                ),
                (
                    "months_since_training",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_current", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SELF", "Trainee"),
                            ("FOLLOWUP", "Follow-up response"),
                            ("PROVIDER", "Provider"),
                        ],
                        default="SELF",
                        max_length=10,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="training.trainingenrollment",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_outcomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="TargetRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("sector", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "required",
                    models.JSONField(
                        default=list,
                        help_text='[{"skill": "SQL", "level": "INTERMEDIATE"}]',
                    ),
                ),
                ("soft_skill_min", models.PositiveSmallIntegerField(default=60)),
                ("openings", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="NonPlacementReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SKILL_MISMATCH", "Skill mismatch"),
                            ("LACK_EXPERIENCE", "Lack of experience"),
                            ("LOCATION", "Location constraints"),
                            ("WAGE_EXPECTATION", "Wage expectations"),
                            ("NO_OPPORTUNITIES", "Lack of job opportunities"),
                            ("INCOMPLETE_CERT", "Incomplete certification"),
                            ("COMMUNICATION", "Communication difficulties"),
                            ("PERSONAL", "Personal or logistical barriers"),
                            ("FURTHER_EDUCATION", "Further education"),
                            ("OTHER", "Other or not specified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "categorised_by",
                    models.CharField(
                        default="TRAINEE",
                        help_text="TRAINEE, GEMINI or RULES",
                        max_length=10,
                    ),
                ),
                ("disputed", models.BooleanField(default=False)),
                ("dispute_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="outcomes.employmentoutcome",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_placement_reasons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("employer_email", models.EmailField(blank=True, max_length=254)),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("DISPUTED", "Disputed"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                ("confirmed_role", models.CharField(blank=True, max_length=120)),
                (
                    "confirmed_income",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="outcomes.employmentoutcome",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="FollowUpSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone",
                    models.CharField(
                        choices=[
                            ("D30", "Day 30 · employment status"),
                            ("D90", "Day 90 · employment or job search"),
                            ("D180", "Day 180 · retention and income"),
                            ("D365", "Day 365 · career progression"),
                        ],
                        max_length=5,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-app"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("IVR", "IVR"),
                            ("EMAIL", "Email"),
                        ],
                        default="IN_APP",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("SENT", "Sent"),
                            ("RESPONDED", "Responded"),
                            ("UNREACHABLE", "Unreachable"),
                        ],
                        default="SCHEDULED",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, default=dict)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="training.trainingenrollment",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
                "unique_together": {("enrollment", "milestone")},
            },
        ),
    ]
