# Generated by Django 4.2.30 on 2026-09-26 09:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TAB_SWITCH", "Tab switch"),
                            ("FOCUS_LOST", "Window lost focus"),
                            ("FULLSCREEN_EXIT", "Exited fullscreen"),
                            ("ANSWER_CHANGE", "Answer changed"),
                            ("SKIP", "Question skipped"),
                            ("RESUME", "Session resumed"),
                            ("OFFLINE", "Connectivity lost"),
                            ("ONLINE", "Connectivity restored"),
                            ("COPY_ATTEMPT", "Copy attempt"),
                            ("START", "Started"),
                            ("SUBMIT", "Submitted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("question_id", models.IntegerField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("client_ts", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("SOFT", "Soft skill"), ("TECH", "Technical")],
                        max_length=4,
                    ),
                ),
                ("attempt_no", models.PositiveSmallIntegerField(default=1)),
                ("question_ids", models.JSONField(default=list)),
                (
                    "option_orders",
                    models.JSONField(
                        default=dict,
                        help_text="question_id -> shuffled original option indexes",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict, help_text="question_id -> displayed option index"
                    ),
                ),
                ("visited", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("SUBMITTED", "Submitted"),
                            ("AUTO_SUBMITTED", "Auto-submitted at time limit"),
                        ],
                        default="IN_PROGRESS",
                        max_length=15,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "correct_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("domain_scores", models.JSONField(blank=True, default=dict)),
                ("band", models.CharField(blank=True, max_length=15)),
                ("passed", models.BooleanField(null=True)),
                ("integrity", models.JSONField(blank=True, default=dict)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("NONE", "No review needed"),
                            ("FLAGGED", "Flagged for review"),
                            ("CLEARED", "Cleared"),
                            ("INVALIDATED", "Invalidated"),
                        ],
                        default="NONE",
                        max_length=12,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("system_check", models.JSONField(blank=True, default=dict)),
                ("feedback", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("SOFT", "Soft skill"), ("TECH", "Technical")],
                        max_length=4,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMMUNICATION", "Communication"),
                            ("PROBLEM_SOLVING", "Problem-solving"),
                            ("TEAMWORK", "Teamwork"),
                            ("TIME_MANAGEMENT", "Time management"),
                            ("PROFESSIONALISM", "Professionalism"),
                            ("ADAPTABILITY", "Adaptability"),
                            ("DIGITAL_LITERACY", "Digital literacy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=80)),
                ("difficulty", models.PositiveSmallIntegerField(default=2)),
                ("text", models.TextField()),
                ("options", models.JSONField()),
                ("correct_index", models.PositiveSmallIntegerField()),
                ("explanation", models.TextField(blank=True)),
                ("source", models.CharField(default="SEED", max_length=10)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
