"""Seed question bank. Soft-skill items are situational judgement questions; the keyed answer is the
most constructive workplace response. Technical items test practical understanding."""

# domain: [(text, options, correct_index, explanation)]
SOFT = {
    "COMMUNICATION": [
        ("Your supervisor gives you a long set of instructions quickly and you are unsure about one step. What do you do?",
         ["Guess the step and continue", "Repeat the instructions back briefly and ask about the unclear step", "Ask a co-worker later", "Skip that step"],
         1, "Confirming understanding avoids costly mistakes."),
        ("A customer is speaking angrily about a delayed delivery. What is the best first response?",
         ["Explain it is not your fault", "Listen fully, acknowledge the problem, then explain the next step", "Transfer the call immediately", "Ask them to calm down"],
         1, "Acknowledging the concern first reduces tension."),
        ("You need to inform your team that a meeting has moved. Which message is clearest?",
         ["Meeting changed", "Please check the new time", "Today's 3 pm review is moved to 4:30 pm in Room 2", "Meeting later, see you"],
         2, "Clear messages include what, when and where."),
        ("During a video interview, your internet becomes unstable. What should you do?",
         ["Disconnect without saying anything", "Tell the interviewer, switch off video if needed, and offer to call back", "Keep talking and hope it improves", "End the interview"],
         1, "Informing the other person and offering an alternative is professional."),
    ],
    "PROBLEM_SOLVING": [
        ("A machine at your workstation keeps stopping. What should you do first?",
         ["Hit the machine", "Note when it stops and report it with details to the supervisor", "Ignore it", "Try random repairs"],
         1, "Observing patterns and reporting clearly helps fix the root cause."),
        ("You have two urgent customer orders and stock for only one. What is the best approach?",
         ["Fulfil any one randomly", "Check priorities with your supervisor and inform both customers of timelines", "Cancel both", "Delay both without telling anyone"],
         1, "Escalating trade-offs and communicating timelines is sound judgement."),
        ("A form you fill daily has a step that wastes time. What is the most constructive action?",
         ["Stop doing the step", "Suggest a simpler method to your supervisor with an example", "Complain to co-workers", "Do nothing"],
         1, "Proposing improvements through the right channel is good problem-solving."),
        ("You make an error in a customer bill that was already sent. What do you do?",
         ["Hope nobody notices", "Inform your supervisor, correct it, and send the customer a corrected bill", "Blame the software", "Wait for the customer to complain"],
         1, "Owning and correcting errors quickly builds trust."),
    ],
    "TEAMWORK": [
        ("A team member is struggling to finish their share of a group task. What do you do?",
         ["Report them immediately", "Offer help after finishing your part and agree how to split remaining work", "Ignore it", "Do their work without telling anyone"],
         1, "Supporting colleagues openly strengthens the team."),
        ("Your team disagrees on how to arrange stock in a store. What is the best way forward?",
         ["Follow whoever is loudest", "Discuss options briefly, agree on one, and review results after a week", "Do it your own way", "Leave the decision"],
         1, "Agreeing and reviewing results resolves disagreements constructively."),
        ("A new colleague joins your shift. How can you help them best?",
         ["Let them figure it out", "Show key tasks and safety rules and tell them whom to ask", "Give them the hardest work", "Talk about office gossip"],
         1, "Good onboarding helps the whole team."),
        ("Credit for a successful project was given only to you, though others helped. What do you do?",
         ["Accept it silently", "Thank the manager and mention the team members' contributions", "Say it was luck", "Avoid the topic"],
         1, "Sharing credit builds trust in a team."),
    ],
    "TIME_MANAGEMENT": [
        ("You have five tasks and one is due in an hour. How should you plan?",
         ["Start with the easiest", "Finish the task due in one hour first, then plan the rest by deadline", "Do them randomly", "Wait for instructions"],
         1, "Prioritise by urgency and importance."),
        ("You realise you will miss a deadline. When should you inform your supervisor?",
         ["After the deadline", "As soon as you know, with a revised timeline", "Never", "Only if asked"],
         1, "Early warning lets the team adjust."),
        ("Your shift starts at 9 am and the bus is often late. What is the best habit?",
         ["Arrive whenever the bus comes", "Take an earlier bus and keep a buffer", "Call in sick", "Ask others to cover daily"],
         1, "Building buffers ensures punctuality."),
        ("You keep getting interrupted while doing detailed data entry. What helps most?",
         ["Stop the task", "Block focused time and batch questions for a fixed time", "Work late every day", "Ignore all messages all day"],
         1, "Time-blocking protects focus while staying available."),
    ],
    "PROFESSIONALISM": [
        ("You cannot come to work tomorrow because of a family emergency. What should you do?",
         ["Just not come", "Inform your supervisor as early as possible and hand over urgent work", "Tell a friend to inform later", "Send a message after the shift"],
         1, "Early notice and handover are professional."),
        ("A customer offers you a personal gift to speed up their work. What do you do?",
         ["Accept it quietly", "Politely decline and follow the normal process", "Ask for more", "Accept and share with the team"],
         1, "Declining gifts protects integrity."),
        ("You find a co-worker sharing customer phone numbers on a personal group. What do you do?",
         ["Join the group", "Report it to your supervisor as it breaks data privacy", "Ignore it", "Share it further"],
         1, "Customer data must be protected."),
        ("Your supervisor gives feedback that your reports have errors. How do you respond?",
         ["Argue", "Thank them, ask for examples, and check your reports before submitting", "Ignore it", "Complain to others"],
         1, "Accepting feedback and acting on it shows maturity."),
    ],
    "ADAPTABILITY": [
        ("Your company introduces a new billing software. What is the best response?",
         ["Keep using the old method", "Learn the new software, ask for training, and practise", "Refuse to use it", "Wait for others to learn first"],
         1, "Embracing change keeps you employable."),
        ("You are shifted to a different department for a month. How do you approach it?",
         ["Do the minimum", "Learn the new tasks and see it as a chance to build skills", "Ask to go back immediately", "Complain"],
         1, "A learning attitude helps in new roles."),
        ("A customer requests something outside the usual process. What should you do?",
         ["Refuse without explanation", "Check with your supervisor what is possible and inform the customer", "Promise anything", "Ignore the request"],
         1, "Flexibility within the rules serves customers well."),
        ("Your shift timing changes next week. What do you do?",
         ["Keep coming at the old time", "Plan travel and routine for the new timing and confirm with your supervisor", "Stop coming", "Ask others to swap every day"],
         1, "Planning ahead makes change manageable."),
    ],
    "DIGITAL_LITERACY": [
        ("You receive an SMS saying your bank account will be blocked unless you click a link and share an OTP. What do you do?",
         ["Click and share the OTP", "Ignore the link, never share the OTP, and contact the bank through its official number", "Forward to friends", "Reply with your account number"],
         1, "Banks never ask for OTPs; this is phishing."),
        ("Which is the strongest password?",
         ["123456", "yourname2001", "Tr#9vK!p2mQ", "password"],
         2, "Strong passwords mix letters, numbers and symbols and are not guessable."),
        ("You need to send a resume by email. Which is best?",
         ["Send a blurry phone photo", "Attach a PDF named Firstname_Lastname_Resume.pdf with a short message", "Paste it into the subject line", "Send without subject or message"],
         1, "A clearly named PDF with a short note is professional."),
        ("You are using a public computer at a cyber café to fill a form. What should you do at the end?",
         ["Leave the browser open", "Log out, close the browser, and clear downloaded files", "Save your password", "Nothing"],
         1, "Logging out protects your accounts."),
    ],
}

# skill name: [(topic, difficulty, text, options, correct_index, explanation)]
TECH = {
    "Python Programming": [
        ("Basics", 1, "What is the output of print(3 * '2')?", ["6", "222", "32", "Error"], 1, "Multiplying a string repeats it."),
        ("Data structures", 1, "Which Python type stores key-value pairs?", ["list", "tuple", "dict", "set"], 2, "A dict maps keys to values."),
        ("Control flow", 2, "What does range(2, 8, 2) produce?", ["2, 4, 6", "2, 4, 6, 8", "2, 3, 4, 5, 6, 7", "4, 6, 8"], 0, "Stop is exclusive, step is 2."),
        ("Code tracing", 2, "x = [1, 2, 3]; y = x; y.append(4). What is x?", ["[1, 2, 3]", "[1, 2, 3, 4]", "[4]", "Error"], 1, "y refers to the same list object."),
        ("Functions", 2, "What does a function return if it has no return statement?", ["0", "An empty string", "None", "It raises an error"], 2, "Python returns None by default."),
        ("Code tracing", 3, "What is len({'a': 1, 'b': 2, 'a': 3})?", ["3", "2", "1", "Error"], 1, "Duplicate keys overwrite, leaving 2 keys."),
        ("Files", 2, "Which statement safely opens and automatically closes a file?", ["open('f.txt')", "with open('f.txt') as f:", "file('f.txt')", "read('f.txt')"], 1, "The with block closes the file."),
        ("Errors", 3, "Which block runs whether or not an exception occurs?", ["except", "else", "finally", "raise"], 2, "finally always runs."),
        ("Data structures", 3, "What is [x*x for x in range(4) if x % 2 == 0]?", ["[0, 4]", "[0, 1, 4, 9]", "[4, 16]", "[1, 9]"], 0, "Even x in 0..3 are 0 and 2."),
    ],
    "SQL": [
        ("Basics", 1, "Which clause filters rows before grouping?", ["ORDER BY", "WHERE", "HAVING", "GROUP BY"], 1, "WHERE filters rows; HAVING filters groups."),
        ("Basics", 1, "Which query returns all columns from table sales?", ["GET * FROM sales", "SELECT ALL sales", "SELECT * FROM sales", "SHOW sales"], 2, "SELECT * returns all columns."),
        ("Aggregation", 2, "Which query counts orders per city?", ["SELECT city, COUNT(*) FROM orders GROUP BY city", "SELECT COUNT(city) FROM orders", "SELECT city FROM orders ORDER BY COUNT", "SELECT * FROM orders GROUP BY COUNT"], 0, "GROUP BY with COUNT gives per-group totals."),
        ("Joins", 2, "An INNER JOIN returns...", ["All rows from both tables", "Only rows with matching keys in both tables", "All rows from the left table", "Only unmatched rows"], 1, "INNER JOIN keeps matches only."),
        ("Joins", 3, "To list all customers including those with no orders, use...", ["INNER JOIN orders", "LEFT JOIN orders from customers", "RIGHT JOIN customers from orders only", "CROSS JOIN"], 1, "LEFT JOIN keeps all rows of the left table."),
        ("Aggregation", 3, "Which clause keeps only cities with more than 10 orders?", ["WHERE COUNT(*) > 10", "HAVING COUNT(*) > 10", "LIMIT 10", "ORDER BY 10"], 1, "Filter aggregated groups with HAVING."),
        ("Nulls", 2, "How do you find rows where phone is missing?", ["phone = NULL", "phone IS NULL", "phone == ''", "phone NULL"], 1, "Use IS NULL."),
        ("Modification", 2, "Which statement changes existing rows?", ["INSERT", "ALTER", "UPDATE", "CREATE"], 2, "UPDATE modifies existing data."),
    ],
    "MS Excel": [
        ("Formulas", 1, "Which formula adds values in A1 to A10?", ["=ADD(A1:A10)", "=SUM(A1:A10)", "=TOTAL(A1,A10)", "=A1+A10"], 1, "SUM adds a range."),
        ("References", 2, "In =B2*$C$1, what does $C$1 mean when copied down?", ["It changes to C2", "It stays fixed at C1", "It becomes an error", "It becomes D1"], 1, "$ makes the reference absolute."),
        ("Lookup", 2, "Which function finds a price for a product code in a table?", ["COUNTIF", "VLOOKUP", "CONCAT", "ROUND"], 1, "VLOOKUP/XLOOKUP retrieves values by key."),
        ("Conditional", 2, "=IF(B2>=40,\"Pass\",\"Fail\") returns what when B2 is 40?", ["Pass", "Fail", "40", "Error"], 0, ">= includes 40."),
        ("Summaries", 2, "Which feature quickly summarises sales by region and month?", ["Freeze panes", "Pivot table", "Spell check", "Wrap text"], 1, "Pivot tables summarise data."),
        ("Conditional", 3, "Which formula totals sales in column C only where column B is 'Pune'?", ["=SUM(C:C,\"Pune\")", "=SUMIF(B:B,\"Pune\",C:C)", "=COUNTIF(C:C,\"Pune\")", "=IF(B:B=\"Pune\",C:C)"], 1, "SUMIF(range, criteria, sum_range)."),
        ("Data", 1, "What is the fastest way to show only rows for one district?", ["Delete other rows", "Apply a filter", "Hide columns", "Change font"], 1, "Filters hide non-matching rows without deleting."),
        ("Formatting", 3, "Cells show ##### after entering a date. What is the likely fix?", ["Retype the date", "Widen the column", "Delete the cell", "Change the formula"], 1, "The column is too narrow to display the value."),
    ],
    "Tally & GST Accounting": [
        ("Basics", 1, "Which voucher records a cash sale in Tally?", ["Payment", "Sales", "Contra", "Journal"], 1, "Sales vouchers record sales."),
        ("Basics", 1, "Transferring cash from the bank to the cash-in-hand uses which voucher?", ["Contra", "Receipt", "Purchase", "Sales"], 0, "Contra is for cash/bank transfers."),
        ("GST", 2, "For an intra-state sale in Maharashtra, which taxes apply?", ["IGST only", "CGST and SGST", "UTGST only", "No GST"], 1, "Intra-state supplies attract CGST + SGST."),
        ("GST", 2, "For an 18% GST item worth ₹1,000 sold within the state, CGST is...", ["₹180", "₹90", "₹18", "₹9"], 1, "18% splits into 9% CGST + 9% SGST."),
        ("Accounting", 2, "Rent paid is which type of account?", ["Personal", "Real", "Nominal", "Capital"], 2, "Expenses are nominal accounts."),
        ("GST", 3, "Which return summarises outward supplies monthly?", ["GSTR-1", "GSTR-9", "ITR-4", "TDS-26Q"], 0, "GSTR-1 reports outward supplies."),
        ("Reconciliation", 3, "A cheque issued but not yet cleared causes the bank balance to be...", ["Lower than the books", "Higher than the books", "Equal", "Zero"], 1, "The bank has not deducted it yet."),
        ("Accounting", 2, "Which is the golden rule for real accounts?", ["Debit the receiver, credit the giver", "Debit what comes in, credit what goes out", "Debit expenses, credit income", "Credit all"], 1, "Real accounts: debit what comes in."),
    ],
    "Electrical Wiring": [
        ("Safety", 1, "Before working on a circuit, what must you do first?", ["Check it with wet hands", "Switch off the supply and test that it is dead", "Remove the fuse while live", "Call the customer"], 1, "Isolate and test before work."),
        ("Basics", 1, "What is the colour of the earth wire in Indian domestic wiring?", ["Red", "Black", "Green", "Blue"], 2, "Green (or green-yellow) is earth."),
        ("Circuits", 2, "Two 10 Ω resistors in series give a total of...", ["5 Ω", "10 Ω", "20 Ω", "100 Ω"], 2, "Series resistances add."),
        ("Circuits", 2, "Two 10 Ω resistors in parallel give a total of...", ["5 Ω", "10 Ω", "20 Ω", "0 Ω"], 0, "Equal parallel resistors halve."),
        ("Formulas", 2, "A 2000 W heater on 230 V draws roughly how much current?", ["0.9 A", "8.7 A", "46 A", "230 A"], 1, "I = P/V = 2000/230 ≈ 8.7 A."),
        ("Protection", 2, "Which device protects people from earth-leakage shock?", ["MCB", "RCCB/ELCB", "Fuse only", "Switch"], 1, "RCCBs trip on leakage current."),
        ("Troubleshooting", 3, "An MCB trips immediately when a fan is switched on. What is the most likely cause?", ["Low voltage", "Short circuit in the fan circuit", "Loose bulb", "Old paint"], 1, "Instant tripping suggests a short."),
        ("Tools", 1, "Which instrument measures voltage, current and resistance?", ["Megger only", "Multimeter", "Tong tester only", "Tester screwdriver"], 1, "A multimeter measures all three."),
    ],
    "Digital Literacy": [
        ("Email", 1, "Which field sends a copy without other recipients seeing it?", ["To", "CC", "BCC", "Subject"], 2, "BCC recipients are hidden."),
        ("Security", 1, "What is two-factor authentication?", ["Using two passwords", "A password plus a second check such as an OTP", "Two email accounts", "Logging in twice"], 1, "2FA adds a second verification factor."),
        ("Files", 2, "Which format is best for sharing a document that should look the same everywhere?", [".docx", ".pdf", ".txt", ".exe"], 1, "PDF preserves layout."),
        ("Security", 2, "A website address for online payment should start with...", ["http://", "https://", "ftp://", "www only"], 1, "https encrypts data in transit."),
        ("Online services", 2, "DigiLocker is mainly used to...", ["Play games", "Store and share official documents digitally", "Send money", "Book tickets"], 1, "DigiLocker stores verified documents."),
        ("Productivity", 2, "Which shortcut copies selected text on most computers?", ["Ctrl + V", "Ctrl + C", "Ctrl + Z", "Ctrl + P"], 1, "Ctrl + C copies."),
        ("Security", 3, "An email from 'hr@g00gle-careers.co' offers a job if you pay a fee. This is likely...", ["A genuine offer", "A phishing or job scam", "A government scheme", "A bank alert"], 1, "Look-alike domains and fees indicate scams."),
        ("Cloud", 3, "Why keep backups of important files in cloud storage?", ["To slow the computer", "To recover files if the device is lost or damaged", "To delete them later", "It is required by law"], 1, "Backups protect against loss."),
    ],
    "Customer Service": [
        ("Greeting", 1, "What is the best way to greet a walk-in customer?", ["Keep using your phone", "Smile, greet, and ask how you can help", "Wait for them to speak", "Point to the shelves"], 1, "A warm greeting opens service."),
        ("Complaints", 2, "A customer wants to return a product without a bill. What do you do?", ["Refuse rudely", "Explain the policy politely and check with the supervisor for options", "Accept anything", "Ignore them"], 1, "Follow policy while staying helpful."),
        ("Needs", 2, "Which question best finds out what a customer needs?", ["Do you want this?", "What will you mainly use it for?", "Are you buying today?", "Do you have money?"], 1, "Open questions reveal needs."),
        ("Billing", 2, "A customer pays ₹500 for a ₹365 item. How much change?", ["₹125", "₹135", "₹145", "₹235"], 1, "500 − 365 = 135."),
        ("Upselling", 3, "A customer buys a phone. What is an appropriate suggestion?", ["Insist on an expensive model", "Offer a suitable cover or screen guard, explaining the benefit", "Add items to the bill without asking", "Nothing at all"], 1, "Relevant, explained suggestions help the customer."),
        ("Complaints", 3, "Which sequence handles a complaint best?", ["Defend, deny, dismiss", "Listen, apologise, solve, follow up", "Transfer, wait, close", "Argue, escalate, leave"], 1, "The LAST approach resolves complaints."),
        ("Etiquette", 1, "On a call, the customer's issue needs research. What do you say?", ["I don't know", "May I place you on hold for two minutes while I check?", "Call back later", "Hang up"], 1, "Ask permission and set a time."),
        ("Records", 2, "Why note customer feedback in the register or system?", ["It is not useful", "To track issues and improve service", "To blame staff", "To share on social media"], 1, "Feedback records drive improvement."),
    ],
    "Web Development": [
        ("HTML", 1, "Which HTML tag creates a hyperlink?", ["<link>", "<a>", "<href>", "<url>"], 1, "Anchor tags create links."),
        ("CSS", 1, "Which CSS property changes text colour?", ["font-color", "text-style", "color", "background"], 2, "The property is color."),
        ("Responsive", 2, "Which makes a layout adapt to phone screens?", ["Fixed pixel widths everywhere", "Media queries and flexible units", "Using tables", "Large images"], 1, "Media queries and flexible units enable responsiveness."),
        ("JavaScript", 2, "What does document.querySelector('#name') return?", ["All elements with class name", "The first element with id 'name'", "A new element", "The page title"], 1, "# selects by id."),
        ("JavaScript", 3, "What is logged: console.log(typeof [])?", ["array", "object", "list", "undefined"], 1, "Arrays are objects in JavaScript."),
        ("HTTP", 2, "Which HTTP method is typically used to submit a new form record to an API?", ["GET", "POST", "DELETE", "HEAD"], 1, "POST creates resources."),
        ("Accessibility", 2, "Why add alt text to images?", ["For SEO only", "So screen readers can describe the image", "To make images load faster", "It is decorative"], 1, "Alt text supports accessibility."),
        ("JavaScript", 3, "What does 'await' do inside an async function?", ["Stops the whole browser", "Pauses the function until a promise settles", "Creates a loop", "Deletes a variable"], 1, "await waits for the promise."),
    ],
}
