# Generated by Django 4.2.30 on 2026-09-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillingProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("GOVT", "Government"),
                            ("PRIVATE", "Private"),
                            ("NGO", "NGO"),
                            ("ITI", "ITI"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("NDB", "Nandurbar"),
                            ("DHL", "Dhule"),
                            ("JLG", "Jalgaon"),
                            ("BLD", "Buldhana"),
                            ("AKL", "Akola"),
                            ("AMR", "Amravati"),
                            ("NGP", "Nagpur"),
                            ("BHN", "Bhandara"),
                            ("GND", "Gondia"),
                            ("PLG", "Palghar"),
                            ("NSK", "Nashik"),
                            ("AUR", "Chh. Sambhajinagar"),
                            ("JLN", "Jalna"),
                            ("WSM", "Washim"),
                            ("YTL", "Yavatmal"),
                            ("WRD", "Wardha"),
                            ("CHD", "Chandrapur"),
                            ("GDC", "Gadchiroli"),
                            ("MSU", "Mumbai Suburban"),
                            ("THN", "Thane"),
                            ("AHM", "Ahilyanagar"),
                            ("BED", "Beed"),
                            ("PBN", "Parbhani"),
                            ("HNG", "Hingoli"),
                            ("NDD", "Nanded"),
                            ("MUM", "Mumbai City"),
                            ("RGD", "Raigad"),
                            ("PNE", "Pune"),
                            ("DRS", "Dharashiv"),
                            ("LTR", "Latur"),
                            ("RTN", "Ratnagiri"),
                            ("STR", "Satara"),
                            ("SLP", "Solapur"),
                            ("SDG", "Sindhudurg"),
                            ("KLP", "Kolhapur"),
                            ("SNG", "Sangli"),
                        ],
                        max_length=3,
                    ),
                ),
                ("accreditation", models.CharField(blank=True, max_length=80)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "issuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="providers",
                        to="credentials.issuer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillingProgramme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("sector", models.CharField(max_length=80)),
                (
                    "funding_scheme",
                    models.CharField(
                        help_text="PMKVY, State scheme, CSR, etc.", max_length=80
                    ),
                ),
                ("duration_hours", models.PositiveIntegerField(default=120)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("ONLINE", "Online"),
                            ("BLENDED", "Blended"),
                            ("OJT", "On-the-job"),
                        ],
                        default="CLASSROOM",
                        max_length=10,
                    ),
                ),
                ("nsqf_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("qp_code", models.CharField(blank=True, max_length=30)),
                ("target_skills", models.JSONField(blank=True, default=list)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("NDB", "Nandurbar"),
                            ("DHL", "Dhule"),
                            ("JLG", "Jalgaon"),
                            ("BLD", "Buldhana"),
                            ("AKL", "Akola"),
                            ("AMR", "Amravati"),
                            ("NGP", "Nagpur"),
                            ("BHN", "Bhandara"),
                            ("GND", "Gondia"),
                            ("PLG", "Palghar"),
                            ("NSK", "Nashik"),
                            ("AUR", "Chh. Sambhajinagar"),
                            ("JLN", "Jalna"),
                            ("WSM", "Washim"),
                            ("YTL", "Yavatmal"),
                            ("WRD", "Wardha"),
                            ("CHD", "Chandrapur"),
                            ("GDC", "Gadchiroli"),
                            ("MSU", "Mumbai Suburban"),
                            ("THN", "Thane"),
                            ("AHM", "Ahilyanagar"),
                            ("BED", "Beed"),
                            ("PBN", "Parbhani"),
                            ("HNG", "Hingoli"),
                            ("NDD", "Nanded"),
                            ("MUM", "Mumbai City"),
                            ("RGD", "Raigad"),
                            ("PNE", "Pune"),
                            ("DRS", "Dharashiv"),
                            ("LTR", "Latur"),
                            ("RTN", "Ratnagiri"),
                            ("STR", "Satara"),
                            ("SLP", "Solapur"),
                            ("SDG", "Sindhudurg"),
                            ("KLP", "Kolhapur"),
                            ("SNG", "Sangli"),
                        ],
                        max_length=3,
                    ),
                ),
                ("cohort_size", models.PositiveIntegerField(default=30)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="training.skillingprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cohort", models.CharField(blank=True, max_length=20)),
                (
                    "enrolled_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("attendance_pct", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "Enrolled"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("DROPOUT", "Dropped out"),
                        ],
                        default="ENROLLED",
                        max_length=12,
                    ),
                ),
                ("provider_confirmed", models.BooleanField(default=False)),
                ("certificate_number", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="training.skillingprogramme",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_on"],
                "unique_together": {("trainee", "programme")},
            },
        ),
    ]
