# Generated by Django 4.2.30 on 2026-09-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/%Y/%m/"
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=200)),
                (
                    "file_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("holder_name", models.CharField(max_length=150)),
                ("issuer_name", models.CharField(max_length=200)),
                ("cert_number", models.CharField(db_index=True, max_length=60)),
                ("course_name", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("verification_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DOCUMENT_CHECKED", "Document checked"),
                            ("ISSUER_VERIFIED", "Issuer verified"),
                            ("PARTIALLY_VERIFIED", "Partially verified"),
                            ("MANUAL_REVIEW", "Manual review"),
                            ("REJECTED", "Rejected"),
                            ("VERIFICATION_UNAVAILABLE", "Verification unavailable"),
                        ],
                        default="PENDING",
                        max_length=25,
                    ),
                ),
                ("checks", models.JSONField(blank=True, default=list)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "issuer_type",
                    models.CharField(
                        choices=[
                            ("SSC", "Sector Skill Council"),
                            ("GOVT", "Government body"),
                            ("PROVIDER", "Training provider"),
                            ("PRIVATE", "Private platform"),
                        ],
                        max_length=10,
                    ),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("supports_lookup", models.BooleanField(default=True)),
                (
                    "verification_url_prefix",
                    models.CharField(blank=True, max_length=200),
                ),
                ("is_authorised", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING", "Programming"),
                            ("DATA", "Data"),
                            ("ACCOUNTING", "Accounting"),
                            ("ELECTRICAL", "Electrical"),
                            ("DIGITAL", "Digital literacy"),
                            ("TRADE", "Trade skills"),
                            ("HEALTHCARE", "Healthcare"),
                            ("RETAIL", "Retail & sales"),
                            ("COMMUNICATION", "Communication"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SkillRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SELF", "Self-declared"),
                            ("CERTIFICATE", "Certificate"),
                            ("TRAINING", "Training"),
                        ],
                        default="SELF",
                        max_length=12,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("NONE", "No experience"),
                            ("LT1", "Less than 1 year"),
                            ("1TO3", "1 to 3 years"),
                            ("GT3", "More than 3 years"),
                        ],
                        default="NONE",
                        max_length=5,
                    ),
                ),
                ("evidence_note", models.CharField(blank=True, max_length=255)),
                (
                    "assessment_status",
                    models.CharField(
                        choices=[
                            ("NOT_ASSESSED", "Not assessed"),
                            ("PENDING", "Assessment pending"),
                            ("PASSED", "Passed"),
                            ("NEEDS_IMPROVEMENT", "Needs improvement"),
                            ("UNDER_REVIEW", "Under review"),
                        ],
                        default="NOT_ASSESSED",
                        max_length=20,
                    ),
                ),
                (
                    "competency_level",
                    models.CharField(default="NOT_ASSESSED", max_length=15),
                ),
                ("best_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_assessed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credentials.certificaterecord",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credentials.skilltaxonomy",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["skill__name"],
            },
        ),
        migrations.CreateModel(
            name="IssuedCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cert_number", models.CharField(max_length=60)),
                ("holder_name", models.CharField(max_length=150)),
                ("course_name", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("holder_uti", models.CharField(blank=True, max_length=24)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued",
                        to="credentials.issuer",
                    ),
                ),
            ],
        ),
    ]
