# Generated by Django 4.2.30 on 2026-09-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterecord",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="training.trainingenrollment",
            ),
        ),
        migrations.AddField(
            model_name="certificaterecord",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="credentials.issuer",
            ),
        ),
        migrations.AddField(
            model_name="certificaterecord",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificaterecord",
            name="trainee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillrecord",
            unique_together={("trainee", "skill")},
        ),
        migrations.AlterUniqueTogether(
            name="issuedcertificate",
            unique_together={("issuer", "cert_number")},
        ),
    ]
