# Generated by Django 4.2.30 on 2026-09-26 09:10

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TRAINEE", "Trainee"),
                            ("PROVIDER", "Training provider"),
                            ("EMPLOYER", "Employer"),
                            ("OFFICER", "Verification officer"),
                            ("ADMIN", "Government administrator"),
                        ],
                        default="TRAINEE",
                        max_length=12,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=15)),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NDB", "Nandurbar"),
                            ("DHL", "Dhule"),
                            ("JLG", "Jalgaon"),
                            ("BLD", "Buldhana"),
                            ("AKL", "Akola"),
                            ("AMR", "Amravati"),
                            ("NGP", "Nagpur"),
                            ("BHN", "Bhandara"),
                            ("GND", "Gondia"),
                            ("PLG", "Palghar"),
                            ("NSK", "Nashik"),
                            ("AUR", "Chh. Sambhajinagar"),
                            ("JLN", "Jalna"),
                            ("WSM", "Washim"),
                            ("YTL", "Yavatmal"),
                            ("WRD", "Wardha"),
                            ("CHD", "Chandrapur"),
                            ("GDC", "Gadchiroli"),
                            ("MSU", "Mumbai Suburban"),
                            ("THN", "Thane"),
                            ("AHM", "Ahilyanagar"),
                            ("BED", "Beed"),
                            ("PBN", "Parbhani"),
                            ("HNG", "Hingoli"),
                            ("NDD", "Nanded"),
                            ("MUM", "Mumbai City"),
                            ("RGD", "Raigad"),
                            ("PNE", "Pune"),
                            ("DRS", "Dharashiv"),
                            ("LTR", "Latur"),
                            ("RTN", "Ratnagiri"),
                            ("STR", "Satara"),
                            ("SLP", "Solapur"),
                            ("SDG", "Sindhudurg"),
                            ("KLP", "Kolhapur"),
                            ("SNG", "Sangli"),
                        ],
                        max_length=3,
                    ),
                ),
                ("preferred_language", models.CharField(default="en", max_length=5)),
                (
                    "organisation",
                    models.CharField(
                        blank=True,
                        help_text="Employer organisation name",
                        max_length=200,
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("anonymised", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=60)),
                ("entity", models.CharField(blank=True, max_length=60)),
                ("entity_id", models.CharField(blank=True, max_length=64)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("TRAINING_RECORDS", "Store my training records"),
                            (
                                "CERT_VERIFICATION",
                                "Verify my certificates with issuers",
                            ),
                            ("SKILL_ASSESSMENT", "Assess my skills and record results"),
                            (
                                "EMPLOYMENT_FOLLOWUP",
                                "Contact me for employment follow-ups",
                            ),
                            (
                                "GOVT_ANALYTICS",
                                "Include my de-identified data in government analytics",
                            ),
                            (
                                "EMPLOYER_VERIFICATION",
                                "Let employers verify my employment details",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("granted", models.BooleanField()),
                ("version", models.CharField(max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("kind", models.CharField(default="INFO", max_length=20)),
                ("read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TraineeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uti",
                    models.CharField(
                        max_length=24,
                        unique=True,
                        verbose_name="Unique Trainee Identifier",
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Female"),
                            ("M", "Male"),
                            ("O", "Other"),
                            ("N", "Prefer not to say"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("NDB", "Nandurbar"),
                            ("DHL", "Dhule"),
                            ("JLG", "Jalgaon"),
                            ("BLD", "Buldhana"),
                            ("AKL", "Akola"),
                            ("AMR", "Amravati"),
                            ("NGP", "Nagpur"),
                            ("BHN", "Bhandara"),
                            ("GND", "Gondia"),
                            ("PLG", "Palghar"),
                            ("NSK", "Nashik"),
                            ("AUR", "Chh. Sambhajinagar"),
                            ("JLN", "Jalna"),
                            ("WSM", "Washim"),
                            ("YTL", "Yavatmal"),
                            ("WRD", "Wardha"),
                            ("CHD", "Chandrapur"),
                            ("GDC", "Gadchiroli"),
                            ("MSU", "Mumbai Suburban"),
                            ("THN", "Thane"),
                            ("AHM", "Ahilyanagar"),
                            ("BED", "Beed"),
                            ("PBN", "Parbhani"),
                            ("HNG", "Hingoli"),
                            ("NDD", "Nanded"),
                            ("MUM", "Mumbai City"),
                            ("RGD", "Raigad"),
                            ("PNE", "Pune"),
                            ("DRS", "Dharashiv"),
                            ("LTR", "Latur"),
                            ("RTN", "Ratnagiri"),
                            ("STR", "Satara"),
                            ("SLP", "Solapur"),
                            ("SDG", "Sindhudurg"),
                            ("KLP", "Kolhapur"),
                            ("SNG", "Sangli"),
                        ],
                        max_length=3,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BELOW_10", "Below 10th"),
                            ("SSC", "10th (SSC)"),
                            ("HSC", "12th (HSC)"),
                            ("ITI", "ITI"),
                            ("DIPLOMA", "Diploma"),
                            ("GRADUATE", "Graduate"),
                            ("POSTGRADUATE", "Postgraduate"),
                        ],
                        max_length=15,
                    ),
                ),
                ("qualification", models.CharField(blank=True, max_length=150)),
                ("preferred_roles", models.JSONField(blank=True, default=list)),
                ("training_interests", models.JSONField(blank=True, default=list)),
                ("career_goals", models.TextField(blank=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("EMPLOYED", "Employed"),
                            ("SELF_EMPLOYED", "Self-employed"),
                            ("APPRENTICE", "Apprentice"),
                            ("SEEKING", "Seeking employment"),
                            ("HIGHER_EDUCATION", "Higher education"),
                            ("CONTINUING_TRAINING", "Continuing training"),
                            ("OTHER", "Other"),
                        ],
                        default="SEEKING",
                        max_length=20,
                    ),
                ),
                (
                    "experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "consent_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cache of latest consent per purpose",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UTISequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=3)),
                ("year", models.PositiveIntegerField()),
                ("last", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("district", "year")},
            },
        ),
    ]
